language: php
dist: trusty
php:
  - 7.1
  - 7.2
  - 7.3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd
  - sudo beanstalkd -l 127.0.0.1 -p 11300 &

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist
